struc_13 macro p0,p1,p2
    dc.b p0
    dc.b p1
    dc.b p2
struc_13 endm

struc_12 macro p0,p1
    dc.w p0
    dc.w p1
struc_12 endm

struc_11 macro p0,p1
    dc.w p0
    dc.w p1
struc_11 endm

struc_C8E4 macro p0,p1
    dc.w p0
    dc.w p1
struc_C8E4 endm

nemesis_ram macro p0,p1
    dc.l p0
    dc.l p1
nemesis_ram endm

struc_14 macro p0,p1
    dc.w p0
    dc.w p1
struc_14 endm

struc_65_v2 macro p0,p1,p2,p3,p4,p5,p6,p7,p8
    dc.l p0
    dc.w p1
    dc.b p2
    dc.b p3
    dc.b p4
    dc.b p5
    dc.w p6
    dc.w p7
    dc.l p8
struc_65_v2 endm

struc_C04E macro p0,p1
    dc.w p0
    dc.w p1
struc_C04E endm

struc_18 macro p0,p1
    dc.b p0
    dc.b p1
struc_18 endm

struc_A84C macro p0,p1
    dc.w p0
    dc.w p1
struc_A84C endm

struc_C83C macro p0,p1
    dc.w p0
    dc.w p1
struc_C83C endm

struc_BCC0 macro p0,p1
    dc.w p0
    dc.w p1
struc_BCC0 endm

struc_C7E8 macro p0,p1
    dc.w p0
    dc.w p1
struc_C7E8 endm

struc_12A9A8 macro p0,p1
    dc.w p0
    dc.w p1
struc_12A9A8 endm

struc_C1D8 macro p0,p1
    dc.w p0
    dc.w p1
struc_C1D8 endm

struc_C396 macro p0,p1
    dc.w p0
    dc.w p1
struc_C396 endm

struc_9 macro p0,p1,p2,p3,p4
    dc.b p0
    dc.b p1
    dc.b p2
    dc.b p3
    dc.l p4
struc_9 endm

struc_8 macro p0,p1,p2,p3,p4
    dc.w p0
    dc.w p1
    dc.w p2
    dc.w p3
    dc.w p4
struc_8 endm

struc_A8CC macro p0,p1
    dc.w p0
    dc.w p1
struc_A8CC endm

struc_1 macro p0,p1,p2
    dc.w p0
    dc.w p1
    dc.w p2
struc_1 endm

struc_60 macro p0,p1,p2
    dc.w p0
    dc.w p1
    dc.w p2
struc_60 endm

struc_C2AA macro p0,p1
    dc.w p0
    dc.w p1
struc_C2AA endm

struc_48 macro p0,p1
    dc.l p0
    dc.l p1
struc_48 endm

nemesis_vram macro p0,p1
    dc.l p0
    dc.l p1
nemesis_vram endm

nemesis_to_vram1 macro p0,p1
    dc.l p0
    dc.l p1
nemesis_to_vram1 endm

kosinski_data macro p0,p1
    dc.l p0
    dc.l p1
kosinski_data endm

struc_44 macro p0,p1
    dc.w p0
    dc.w p1
struc_44 endm

struc_45 macro p0,p1,p2
    dc.w p0
    dc.b p1
    dc.b p2
struc_45 endm

struc_46 macro p0,p1
    dc.l p0
    dc.l p1
struc_46 endm

struc_47 macro p0,p1
    dc.b p0
    dc.b p1
struc_47 endm

struc_19 macro p0,p1
    dc.w p0
    dc.w p1
struc_19 endm

struc_42 macro p0,p1,p2
    dc.w p0
    dc.w p1
    dc.l p2
struc_42 endm

struc_43 macro p0,p1,p2,p3,p4
    dc.w p0
    dc.w p1
    dc.w p2
    dc.l p3
    dc.l p4
struc_43 endm

struc_C66C macro p0,p1
    dc.w p0
    dc.w p1
struc_C66C endm

struc_BE44 macro p0,p1
    dc.w p0
    dc.w p1
struc_BE44 endm

struc_64 macro p0,p1,p2,p3
    dc.b p0
    dc.b p1
    dc.b p2
    dc.b p3
struc_64 endm

struc_49 macro p0,p1,p2,p3
    dc.b p0
    dc.b p1
    dc.b p2
    dc.b p3
struc_49 endm

struc_BD98 macro p0,p1
    dc.w p0
    dc.w p1
struc_BD98 endm

struc_58 macro p0,p1
    dc.w p0
    dc.w p1
struc_58 endm

ram_vram_send macro p0,p1,p2,p3
    dc.l p0
    dc.l p1
    dc.w p2
    dc.w p3
ram_vram_send endm

weapon_type macro p0,p1
    dc.w p0
    dc.w p1
weapon_type endm

struc_C9B0 macro p0,p1
    dc.w p0
    dc.w p1
struc_C9B0 endm

struc_C588 macro p0,p1
    dc.w p0
    dc.w p1
struc_C588 endm

struc_C730 macro p0,p1
    dc.w p0
    dc.w p1
struc_C730 endm

struc_A8EC macro p0,p1
    dc.w p0
    dc.w p1
struc_A8EC endm

struc_61 macro p0,p1,p2,p3
    dc.w p0
    dc.w p1
    dc.w p2
    dc.w p3
struc_61 endm

struc_C154 macro p0,p1
    dc.w p0
    dc.w p1
struc_C154 endm

struc_C45C macro p0,p1
    dc.w p0
    dc.w p1
struc_C45C endm

struc_C508 macro p0,p1
    dc.w p0
    dc.w p1
struc_C508 endm

raw_data macro p0,p1,p2,p3
    dc.l p0
    dc.l p1
    dc.w p2
    dc.w p3
raw_data endm

struc_52 macro p0,p1
    dc.l p0
    dc.l p1
struc_52 endm

struc_59 macro p0,p1,p2
    dc.w p0
    dc.w p1
    dc.w p2
struc_59 endm

struc_BF0E macro p0,p1
    dc.w p0
    dc.w p1
struc_BF0E endm

struc_57 macro p0,p1
    dc.l p0
    dc.l p1
struc_57 endm

struc_30 macro p0,p1,p2
    dc.w p0
    dc.w p1
    dc.w p2
struc_30 endm

struc_54 macro p0,p1
    dc.l p0
    dc.l p1
struc_54 endm

struc_53 macro p0,p1,p2,p3
    dc.w p0
    dc.w p1
    dc.l p2
    dc.l p3
struc_53 endm

enigma_data macro p0,p1,p2
    dc.l p0
    dc.l p1
    dc.w p2
enigma_data endm

struc_51 macro p0,p1
    dc.b p0
    dc.b p1
struc_51 endm

struc_50 macro p0,p1,p2,p3
    dc.w p0
    dc.w p1
    dc.w p2
    dc.w p3
struc_50 endm

