lvl_start_params macro p0,p1,p2,p3,p4,p5,p6,p7,p8
    dc.w p0
    dc.w p1
    dc.w p2
    dc.w p3
    dc.w p4
    dc.w p5
    dc.w p6
    dc.b p7
    dc.b p8
lvl_start_params endm

lvl_params2 macro p0,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16
    dc.w p0
    dc.w p1
    dc.w p2
    dc.w p3
    dc.w p4
    dc.w p5
    dc.w p6
    dc.w p7
    dc.w p8
    dc.w p9
    dc.w p10
    dc.w p11
    dc.w p12
    dc.w p13
    dc.w p14
    dc.w p15
    dc.w p16
lvl_params2 endm

